### ISSUE TITLE
[BUG] 当前佩戴的粉丝牌在每天第一次运行时读取不到

### ISSUE THREAD

**Issue by JokerQyou** [ThreeCatsLoveFish/MedalHelper#15]
**Describe the bug**

设置的是每天零点之后的几分钟运行一次定时任务。当前佩戴的粉丝牌似乎不会去执行任务，日志里没有打印（其他直播间的任务都运行了）。但是手动再运行一次 start 命令就又可以正常运行。

**To Reproduce**

上文已经有写，就是固定佩戴一个粉丝牌，然后定时任务每天运行一次。任务结束后其他直播间的任务完成了，但这一个直播间的任务没有开始，因为一开始就没读取到这个牌子。
因为我是固定佩戴那一个粉丝牌，所以目前只观察到这一个直播间会这样。下次定时任务前我换个牌子看看。

**Expected behavior**

可以正常完成所有牌子的任务。

**Screenshots**

暂无。

**Docker (please complete the following information):**
 - Docker Version commit ID 100e94e5b6d50505ee009560f8ca49bc857566d7.

**Additional context**

None

**Comment by ThreeCatsLoveFish** [comment]
这个bug我其实今早就发现了，但是我当时没想通哪里的问题，我之后修一下


------------------ 原始邮件 ------------------
From: Joker_ ***@***.***&gt;
发送时间: 05/31/2022, 00:18
To: ThreeCatsLoveFish/MedalHelper ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
Subject: Re: [ThreeCatsLoveFish/MedalHelper] [BUG] 当前佩戴的粉丝牌在每天第一次运行时读取不到 (Issue #15)





 
Describe the bug
 
设置的是每天零点之后的几分钟运行一次定时任务。当前佩戴的粉丝牌似乎不会去执行任务，日志里没有打印（其他直播间的任务都运行了）。但是手动再运行一次 start 命令就又可以正常运行。
 
To Reproduce
 
上文已经有写，就是固定佩戴一个粉丝牌，然后定时任务每天运行一次。任务结束后其他直播间的任务完成了，但这一个直播间的任务没有开始，因为一开始就没读取到这个牌子。
 因为我是固定佩戴那一个粉丝牌，所以目前只观察到这一个直播间会这样。下次定时任务前我换个牌子看看。
 
Expected behavior
 
可以正常完成所有牌子的任务。
 
Screenshots
 
暂无。
 
Docker (please complete the following information):
  
Docker Version commit ID 100e94e. 
 
Additional context
 
None

**Comment by ThreeCatsLoveFish** [comment]
这个case奇怪的点就是我重新单独跑一边start是一切正常的，我觉得可能是佩戴的勋章单独传了一个字段

**Comment by ThreeCatsLoveFish** [comment]
我现在加上新逻辑，让我每次在最开始跑的时候先卸下粉丝牌获得全部的牌子，再佩戴上对应牌子去房间打卡 #17 ，最后再佩戴回原本的勋章

**Comment by JokerQyou** [comment]
> 这个case奇怪的点就是我重新单独跑一边start是一切正常的，佩戴的勋章单独传了一个字段，但是我代码这块逻辑也做好了，没有问题才对

是的。这太奇怪了。

我今天看到之后试了 start 一次，等它跑完之后发现漏了另一个牌子（没有佩戴的牌子）。晚上我再看看怎么回事。

**Comment by ThreeCatsLoveFish** [comment]
> > 这个case奇怪的点就是我重新单独跑一边start是一切正常的，佩戴的勋章单独传了一个字段，但是我代码这块逻辑也做好了，没有问题才对
> 
> 是的。这太奇怪了。
> 
> 我今天看到之后试了 start 一次，等它跑完之后发现漏了另一个牌子（没有佩戴的牌子）。晚上我再看看怎么回事。

我觉得我完全有理由怀疑不是我脚本的问题，而是b站处理勋章接口的时候的问题

btw 新功能上线了，今晚看下会出现什么有趣的事情 😄

**Comment by ThreeCatsLoveFish** [comment]
@JokerQyou 这个case今天依旧存在，但是有意思的是这个牌子我第一次其实获得到了，但是他没有进我的打卡列表中，而是被过滤掉了，而我的过滤逻辑之后三个，黑名单、房间号id和今日亲密度，但是我啥都没干重试第二遍就好了，所以确实是接口的问题

**Comment by ThreeCatsLoveFish** [comment]
这个就这样吧，第二遍重试目前一直是ok的，我为了这个功能把roomID为0的过滤去掉是不大合理的，接口的bug不能怪我，要怪叔叔:smile:
